os: Visual Studio 2015
version: 1.0.{build}

environment:
  CLI_VERSION: 1.0.0-rc3-004530
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

branches:
  only:
    - master

build_script:
  - ps: dotnet --info
  - ps: .\Build.ps1

artifacts:
  - path: artifacts

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off
