version: 1.0.{build}

assembly_info:
  patch: true
  file: AssemblyVersion.cs
  assembly_version: "1.0.0.0"
  assembly_file_version: "{version}.0"
  assembly_informational_version: "{version}.0"

build:
  project: src\ProjectEuler.msbuild
  verbosity: minimal

after_build:
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "src\BuildOutput\ProjectEuler_coverage.xml"

artifacts:
  - path: src\BuildOutput\ProjectEuler.exe

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off
